basePath: /
definitions:
  models.AccountRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.AdminAccountRequest:
    properties:
      balance:
        type: number
      isAdmin:
        type: boolean
      password:
        type: string
      username:
        type: string
    type: object
  models.AdminAccountResponse:
    properties:
      balance:
        type: number
      id:
        type: integer
      isAdmin:
        type: boolean
      username:
        type: string
    type: object
  models.Response:
    properties:
      message: {}
    type: object
  models.TransportRequest:
    properties:
      canBeRented:
        type: boolean
      color:
        type: string
      dayPrice:
        type: number
      description:
        type: string
      identifier:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      minutePrice:
        type: number
      model:
        type: string
      transportType:
        type: string
    type: object
  models.TransportResponse:
    properties:
      canBeRented:
        type: boolean
      color:
        type: string
      dayPrice:
        type: number
      description:
        type: string
      id:
        type: integer
      identifier:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      minutePrice:
        type: number
      model:
        type: string
      transportType:
        type: string
    type: object
host: localhost:2024
info:
  contact: {}
  title: SimbirGO
  version: "1.0"
paths:
  /api/Account/Me:
    get:
      consumes:
      - application/json
      description: Get Profile
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Me
      tags:
      - Account
  /api/Account/SignIn:
    post:
      consumes:
      - application/json
      description: Sign In
      operationId: sign-in
      parameters:
      - description: Sign In Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.AccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: SignIn
      tags:
      - Account
  /api/Account/SignOut:
    post:
      consumes:
      - application/json
      description: Sign Out
      operationId: sign-out
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: SignOut
      tags:
      - Account
  /api/Account/SignUp:
    post:
      consumes:
      - application/json
      description: Sign Up
      operationId: sign-up
      parameters:
      - description: Sign Up Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.AccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: SignUp
      tags:
      - Account
  /api/Account/Update:
    put:
      consumes:
      - application/json
      description: Update Profile
      operationId: update
      parameters:
      - description: Update Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.AccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - Account
  /api/Admin/Account:
    get:
      consumes:
      - application/json
      description: List Accounts
      operationId: list-accounts
      parameters:
      - description: From
        in: query
        name: from
        required: true
        type: integer
      - description: Count
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AdminAccountResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: ListAccounts
      tags:
      - Admin Account
    post:
      consumes:
      - application/json
      description: Create Account
      operationId: create-account
      parameters:
      - description: Account Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.AdminAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: CreateAccount
      tags:
      - Admin Account
  /api/Admin/Account/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Account
      operationId: delete-account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: DeleteAccount
      tags:
      - Admin Account
    get:
      consumes:
      - application/json
      description: Get Account
      operationId: get-account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AdminAccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: GetAccount
      tags:
      - Admin Account
    put:
      consumes:
      - application/json
      description: Update Account
      operationId: update-account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.AdminAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: UpdateAccount
      tags:
      - Admin Account
  /api/Payment/Hesoyam/{id}:
    post:
      consumes:
      - application/json
      description: Deposit
      operationId: hesoyam
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Hesoyam
      tags:
      - Hesoyam
  /api/Transport:
    post:
      consumes:
      - application/json
      description: Create Transport
      operationId: create-transport
      parameters:
      - description: Transport Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.TransportRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: CreateTransport
      tags:
      - Transport
  /api/Transport/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Transport
      operationId: delete-transport
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: DeleteTransport
      tags:
      - Transport
    get:
      consumes:
      - application/json
      description: Get Transport
      operationId: get-transport
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransportResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: GetTransport
      tags:
      - Transport
    put:
      consumes:
      - application/json
      description: Update Transport
      operationId: update-transport
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transport Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.TransportRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: UpdateTransport
      tags:
      - Transport
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
